---
name: prpro-2024
channels:
  - default
  - conda-forge
dependencies:
  - arviz==0.16.1
  - jupyter==1.0.0
  - jupyterlab==4.0.9
  - pandas==2.1.4
  - pip
  - pooch==1.7.0
  - pymc==5.10.2
  - pytensor=2.18.4
  - seaborn
  - statsmodels
  - tabulate
  - watermark
  - matplotlib==3.8.2
  - xarray==2023.6.0
  - pip:
      - "git+https://github.com/itu-square/causalgraphicalmodels.git" 
        # temporarily, until causalgraphicalmodels stabilize
variables:
  PYTHONNOUSERSITE: '1'
